name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Spam everybody
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: node ./bin/createMessage.js -m "Publication de @s3pweb/release-message-creator, version %s (ancienne %s) :" -w ${{secrets.DISCORD_WEBHOOK_SPAM}}
